#!/bin/sh

fwdir=/etc/firewall
fwreload=0
fwdryrun=0
fwconfig=/etc/sysconfig/iptables

die () {
	echo "ERROR: $*" >&2
	exit 1
}

while getopts rn ch; do
	case $ch in
	(r)	fwreload=1;;
	(n)	fwdryrun=1;;
	esac
done
shift $(( $OPTIND -1 ))

tmpfile=$(mktemp -t firewallXXXXXX)
trap "rm -f $tmpfile" EXIT INT HUP QUIT TERM

for table in $fwdir/*.d; do
	[ -d $table ] || continue

	[ -f $table/head ] && cat $table/head
	cat $table/*.rule
	[ -f $table/foot ] && cat $table/foot
done > $tmpfile

if ! /sbin/iptables-restore -t < $tmpfile; then
	die "errors in firewall configuration"
fi

if [ "$fwdryrun" = 1 ]; then
	cat $tmpfile
else
	cat $tmpfile > $fwconfig

	if [ "$fwreload" = 1 ]; then
		/sbin/service iptables restart
	fi
fi

